platform :ios, '16.0'

target 'Ghost Drawer' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!


 pod 'Swinject'
 pod 'SwinjectStoryboard'

  target 'Ghost DrawerTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'Ghost DrawerUITests' do
    inherit! :complete
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end
